### ISSUE TITLE
Using Soso in my project

### ISSUE THREAD

**Issue by akkartik** [ozkl/soso#2]
I couldn't find any other way to contact you (please let me know if you prefer something else) so thought I'd leave a note here.

I've been building a new, minimal hobbyist computing stack for a couple of years with a goal to be completely independent of C. So far it's a self-hosting syntax for machine code. I can build programs and package them up with a Linux kernel into a bootable disk image that runs on Qemu or a cloud server. But Linux was a pretty heavyweight dependency (even though I've been gradually trimming my fork of it).

Well, I just got it running with Soso, and now I depend on just 33kLoC of C rather than 27MLoC.

https://github.com/akkartik/mu#readme

Thank you very much for Soso! Please let me know if you'd like me to change how/where I give credit to Soso.

**Comment by ozkl** [comment]
I'm glad that you find Soso useful :)
Just putting links to the repository is enough!

By the way, why cloud servers are not supported? Is it because Soso lacking serial console?

**Comment by akkartik** [comment]
I didn't look deeply into it yet. But I plan to do so. I actually don't know much about the OS side of things, but this project is forcing me to learn.

More immediately, I'm planning to submit one PR in a day or three. The heap boundary for a process is hard-coded where it should depend on the size of the code and data segments.
