### ISSUE TITLE
k:PANIC:kernel/vmm.c:401: Page fault in Kernel main thread!!!

### ISSUE THREAD

**Issue by jaychandra6** [ozkl/soso#8]
I tried running it on Limbo x86 emulator on Android and the os halted at this point. what's the reason behind it?

![Screenshot_20210119-200744](https://user-images.githubusercontent.com/58852543/105049161-628c0280-5a92-11eb-8f7c-ad64117fb0b8.png)

**Comment by ozkl** [comment]
Which soso version is this? It seems graphics mode is not enabled, so it falls back to bios fonts.

**Comment by jaychandra6** [comment]
I got it from the releases, version 0.2 I think

**Comment by ozkl** [comment]
I tried it on Limbo and it hanged at the boot loader. Soso runs well on pc with Qemu and VirtualBox. It might be releated to Limbo.

**Comment by jaychandra6** [comment]
Okay, thanks :)
